### ISSUE TITLE
What are the accepted values for `sourceType`?

### ISSUE THREAD

**Issue by ssutar** [dyfactor/dyfactor#10]
What is `sourceType` and what are the accepted values for `sourceType`? 

From the code https://github.com/dyfactor/dyfactor/blob/master/bin/dyfactor-create-plugin#L11  `pluginType` can be `static` or `dynamic` but it does not have any values for `sourceType`

**Comment by chadhietala** [comment]
It should be "template" or "javascript" I believe, but I only ever wrote "template" plugins.
