### ISSUE TITLE
dyfactor-create-plugin issue - type is not defined

### ISSUE THREAD

**Issue by ssutar** [dyfactor/dyfactor#9]
Error while running `dyfactor create-plugin`

```
ReferenceError: type is not defined
```
Originated from https://github.com/dyfactor/dyfactor/blob/master/bin/dyfactor-create-plugin#L15 

Before creating a PR to fix, would like to know what is the `type`. Is it `pluginType` or `sourceType`?

**Comment by chadhietala** [comment]
Yes this should be `sourceType`.
